name: "Delete Packages Manual"

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: '1.0.0'
      nextDevelopmentVersion:
        description: 'Next Development Version ("-SNAPSHOT" muss nicht angegeben werden.)'
        required: true
        default: '1.0.1'

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          #cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Maven config
        run: |
          git config --global user.email "action@hohm.local"
          git config --global user.name "action"
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Delete Package Versions
        uses: actions/delete-package-versions@v2.0.1
        with: 
          package-name: 'test-packae'
          min-versions-to-keep: 10
